# Generated by Django 3.0.3 on 2022-12-08 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_name', models.CharField(max_length=100, verbose_name='name')),
                ('motor_desc', models.TextField(max_length=500, verbose_name='Description of the Vehicle')),
                ('motor_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Vehicle Image')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.CharField(max_length=100, verbose_name='Parts Repaired')),
                ('price', models.IntegerField(verbose_name='Amount')),
                ('t_price', models.IntegerField(verbose_name='Total Amount')),
                ('cat_name4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('checkout', models.CharField(max_length=100, verbose_name='Place')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('cat_name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Diesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('liters', models.IntegerField(default=0, verbose_name='Liters')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('price', models.IntegerField(default=0, verbose_name='Amount')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('cat_name3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Vehicle')),
            ],
        ),
    ]
