# Generated by Django 3.0.3 on 2022-12-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
