# Generated by Django 3.0.3 on 2022-12-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_diesel_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='motor_image',
            new_name='motor_image1',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Vehicle Image 2'),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='cat_name3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category', verbose_name='Category'),
        ),
    ]
