# Generated by Django 3.0.3 on 2022-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20221208_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='motor_desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description of the Vehicle'),
        ),
    ]
