# Generated by Django 3.0.3 on 2022-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20221208_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
