# Generated by Django 3.0.3 on 2023-11-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20221208_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='cat_name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='item',
            field=models.TextField(max_length=100, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Vehicle', verbose_name='Truck'),
        ),
    ]
