# Generated by Django 4.2.19 on 2025-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0002_pendingstockupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='quantity_per_pack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_quantity_or_amount',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
