# Generated by Django 4.2.19 on 2025-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0003_drug_quantity_per_pack_drug_unit_quantity_or_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='unit_quantity_or_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
