# Generated by Django 3.0.3 on 2021-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cowmortality',
            options={'verbose_name_plural': 'Cow mortality'},
        ),
        migrations.RenameField(
            model_name='cowmortality',
            old_name='loaction',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
    ]
