# Generated by Django 3.0.3 on 2021-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_ent', models.CharField(max_length=100, verbose_name='entry type')),
                ('cow_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Cow Records',
            },
        ),
        migrations.CreateModel(
            name='GoatRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat_ent', models.CharField(max_length=100, verbose_name='entry type')),
                ('goat_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Goat Records',
            },
        ),
        migrations.CreateModel(
            name='PigRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_ent', models.CharField(max_length=100, verbose_name='entry type')),
                ('pig_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Pig Records',
            },
        ),
        migrations.CreateModel(
            name='SheepRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheep_ent', models.CharField(max_length=100, verbose_name='entry type')),
                ('sheep_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Sheep Records',
            },
        ),
    ]
