# Generated by Django 4.2.7 on 2025-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='animal_name',
            field=models.CharField(choices=[('pig', 'Pig'), ('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('boar', 'Boar'), ('weaner_pig', 'Weaner (Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('weaner_cattle', 'Weaner (Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner_sheep', 'Weaner (Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner_goat', 'Weaner (Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_name',
            field=models.CharField(choices=[('mortality', 'Mortality'), ('farrowing', 'Farrowing'), ('calving', 'Calving'), ('lambing', 'Lambing'), ('kidding', 'Kidding'), ('procurement', 'Procurement'), ('culling', 'Culling'), ('sale', 'Sale')], max_length=20, unique=True),
        ),
    ]
