# Generated by Django 3.0.3 on 2022-02-28 13:01

from django.db import migrations, models
import farmrecord.validators


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farmrecord.validators.validate_file_size], verbose_name='first image'),
        ),
    ]
