# Generated by Django 3.0.3 on 2021-12-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0002_auto_20211220_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='bull_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='calves',
            field=models.IntegerField(blank=True, null=True, verbose_name='calve(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='cow_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cow(s)'),
        ),
        migrations.RemoveField(
            model_name='cowmortality',
            name='section',
        ),
        migrations.AddField(
            model_name='cowmortality',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='farmrecord.Section', verbose_name='Section'),
        ),
    ]
