# Generated by Django 3.0.3 on 2021-12-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0003_auto_20211221_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowmortality',
            name='user',
        ),
    ]
