# Generated by Django 4.2.19 on 2025-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0003_auto_20250201_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='is_vet',
            field=models.BooleanField(default=False, verbose_name='Is vet'),
        ),
    ]
