# Generated by Django 4.2.19 on 2025-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0004_userp_is_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='is_vet_paddock',
            field=models.BooleanField(default=False, verbose_name='Is vet cattle'),
        ),
        migrations.AddField(
            model_name='userp',
            name='is_vet_piggery',
            field=models.BooleanField(default=False, verbose_name='Is vet piggery'),
        ),
        migrations.AddField(
            model_name='userp',
            name='is_vet_smallruminant',
            field=models.BooleanField(default=False, verbose_name='Is vet small ruminant'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('boar', 'Boar'), ('weaner_pig', 'Weaner(Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('weaner_cattle', 'Weaner(Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner_sheep', 'Weaner(Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner_goat', 'Weaner(Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
    ]
