# Generated by Django 3.0.3 on 2021-12-22 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0004_remove_cowmortality_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of death'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='farmrecord.Section', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='SheepSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ewe_num', models.IntegerField(blank=True, null=True, verbose_name='Ewe(s)')),
                ('ram_num', models.IntegerField(null=True, verbose_name='Ram(s)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)')),
                ('weight', models.IntegerField(verbose_name='Weight(s)')),
                ('price', models.IntegerField(verbose_name='Price(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category10', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='SheepProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ewe_num', models.IntegerField(blank=True, null=True, verbose_name='Ewe(s)')),
                ('ram_num', models.IntegerField(blank=True, null=True, verbose_name='Ram(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category14', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='SheepMortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality', models.CharField(max_length=10, verbose_name='mortality')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200, verbose_name='loaction(s)')),
                ('ewe_num', models.IntegerField(blank=True, null=True, verbose_name='Ewe(s)')),
                ('ram_num', models.IntegerField(blank=True, null=True, verbose_name='Ram(s)')),
                ('lamb', models.IntegerField(blank=True, null=True, verbose_name='lamb(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Cause of death')),
                ('image_1', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='first image')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='farmrecord.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name_plural': 'Sheep mortality',
            },
        ),
        migrations.CreateModel(
            name='SheepCulling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ewe_num', models.IntegerField(blank=True, null=True, verbose_name='Ewe(s)')),
                ('ram_num', models.IntegerField(blank=True, null=True, verbose_name='Ram(s)')),
                ('location', models.CharField(max_length=500, verbose_name='Location(s)')),
                ('reason', models.TextField(blank=True, max_length=500, verbose_name='Reason')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category5', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='PigSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sow_num', models.IntegerField(blank=True, null=True, verbose_name='Sow(s)')),
                ('boar_num', models.IntegerField(null=True, verbose_name='Boar(s)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)')),
                ('weight', models.IntegerField(verbose_name='Weight(s)')),
                ('price', models.IntegerField(verbose_name='Price(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category12', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='PigProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sow_num', models.IntegerField(blank=True, null=True, verbose_name='Sow(s)')),
                ('boar_num', models.IntegerField(blank=True, null=True, verbose_name='Boar(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category15', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='PigMortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality', models.CharField(max_length=10, verbose_name='mortality')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200, verbose_name='loaction(s)')),
                ('sow_num', models.IntegerField(blank=True, null=True, verbose_name='Sow(s)')),
                ('boar_num', models.IntegerField(blank=True, null=True, verbose_name='Boar(s)')),
                ('pigglet', models.IntegerField(blank=True, null=True, verbose_name='Pigglet(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Cause of death')),
                ('image_1', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='first image')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category4', to='farmrecord.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name_plural': 'Pig mortality',
            },
        ),
        migrations.CreateModel(
            name='PigCulling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sow_num', models.IntegerField(blank=True, null=True, verbose_name='Sow(s)')),
                ('boar_num', models.IntegerField(blank=True, null=True, verbose_name='Boar(s)')),
                ('location', models.CharField(max_length=500, verbose_name='Location(s)')),
                ('reason', models.TextField(blank=True, max_length=500, verbose_name='Reason')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category8', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='GoatSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('doe_num', models.IntegerField(blank=True, null=True, verbose_name='Doe(s)')),
                ('buck_num', models.IntegerField(null=True, verbose_name='Buck(s)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)')),
                ('weight', models.IntegerField(verbose_name='Weight(s)')),
                ('price', models.IntegerField(verbose_name='Price(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category11', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='GoatProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('doe_num', models.IntegerField(blank=True, null=True, verbose_name='Doe(s)')),
                ('buck_num', models.IntegerField(blank=True, null=True, verbose_name='Buck(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category13', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='GoatMortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality', models.CharField(max_length=10, verbose_name='mortality')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200, verbose_name='loaction(s)')),
                ('doe_num', models.IntegerField(blank=True, null=True, verbose_name='Doe(s)')),
                ('buck_num', models.IntegerField(blank=True, null=True, verbose_name='Buck(s)')),
                ('kid', models.IntegerField(blank=True, null=True, verbose_name='kid(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Cause of death')),
                ('image_1', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='first image')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='farmrecord.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name_plural': 'Goat mortality',
            },
        ),
        migrations.CreateModel(
            name='GoatCulling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('doe_num', models.IntegerField(blank=True, null=True, verbose_name='Doe(s)')),
                ('buck_num', models.IntegerField(blank=True, null=True, verbose_name='Buck(s)')),
                ('location', models.CharField(max_length=500, verbose_name='Location(s)')),
                ('reason', models.TextField(blank=True, max_length=500, verbose_name='Reason')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category7', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='CowSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cow_num', models.IntegerField(blank=True, null=True, verbose_name='Cow(s)')),
                ('bull_num', models.IntegerField(null=True, verbose_name='Bull(s)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)')),
                ('weight', models.IntegerField(verbose_name='Weight(s)')),
                ('price', models.IntegerField(verbose_name='Price(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category9', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='CowProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cow_num', models.IntegerField(blank=True, null=True, verbose_name='Cow(s)')),
                ('bull_num', models.IntegerField(blank=True, null=True, verbose_name='Bull(s)')),
                ('size', models.CharField(max_length=100, verbose_name='Size(s)')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category16', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='CowCulling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cow_num', models.IntegerField(blank=True, null=True, verbose_name='Cow(s)')),
                ('bull_num', models.IntegerField(blank=True, null=True, verbose_name='Bull(s)')),
                ('location', models.CharField(max_length=500, verbose_name='Location(s)')),
                ('reason', models.TextField(blank=True, max_length=500, verbose_name='Reason')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category6', to='farmrecord.Section', verbose_name='Section')),
            ],
        ),
    ]
