# Generated by Django 3.0.3 on 2021-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0005_auto_20211222_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowprocurement',
            name='size1',
            field=models.CharField(max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='cowsale',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='goatprocurement',
            name='size1',
            field=models.CharField(max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='goatsale',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='pigprocurement',
            name='size1',
            field=models.CharField(max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='pigsale',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='sheepprocurement',
            name='size1',
            field=models.CharField(max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AddField(
            model_name='sheepsale',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AlterField(
            model_name='cowprocurement',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AlterField(
            model_name='goatprocurement',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AlterField(
            model_name='pigprocurement',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AlterField(
            model_name='sheepprocurement',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
    ]
