# Generated by Django 4.2.19 on 2025-10-17 12:06

from django.db import migrations, models
import farmrecord.validators


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0005_userp_is_vet_paddock_userp_is_vet_piggery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='event_description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='description',
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farmrecord.validators.validate_file_size]),
        ),
    ]
