# Generated by Django 4.2.19 on 2025-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0006_rename_event_description_eventtype_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='number_of_animals',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_name',
            field=models.CharField(choices=[('mortality', 'Mortality'), ('farrowing', 'Farrowing'), ('calving', 'Calving'), ('lambing', 'Lambing'), ('kidding', 'Kidding'), ('procurement', 'Procurement'), ('culling', 'Culling'), ('sale', 'Sale')], max_length=20),
        ),
    ]
