# Generated by Django 3.0.3 on 2021-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0006_auto_20211222_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
