# Generated by Django 3.0.3 on 2022-03-10 13:44

from django.db import migrations, models
from farmapp.utils import unique_slug_generatorM


def update_slug(apps, schema_editor):
    Review = apps.get_model('farmrecord', 'Review')

    for instance in Review.objects.all():
      if not instance.slug:
        instance.slug = unique_slug_generatorM(instance, instance.subject, instance.slug)
        instance.save()  

class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0006_review_slug'),
    ]

    operations = [
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
