# Generated by Django 3.0.3 on 2022-03-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0007_auto_20220310_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
