# Generated by Django 3.0.3 on 2022-01-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0007_auto_20211222_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='bull_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='boar_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Boar(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='ram_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ram(s)'),
        ),
    ]
