# Generated by Django 4.2.19 on 2025-10-22 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0007_eventtype_number_of_animals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
