# Generated by Django 4.2.19 on 2025-10-29 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0008_eventtype_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_date', models.DateField(default=django.utils.timezone.now)),
                ('total_animals', models.PositiveIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='censuses', to='farmrecord.animals')),
            ],
        ),
        migrations.CreateModel(
            name='CensusRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_animals', models.PositiveIntegerField()),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmrecord.animaltype')),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='farmrecord.census')),
            ],
        ),
    ]
