# Generated by Django 3.0.3 on 2022-01-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0008_auto_20220108_1442'),
        ('farmrecord', '0008_auto_20220107_1323'),
    ]

    operations = [
    ]
