# Generated by Django 3.0.3 on 2022-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0008_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigmortality',
            name='commentp',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of mortality'),
        ),
    ]
