# Generated by Django 4.2.19 on 2025-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0009_census_censusrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
