# Generated by Django 3.0.3 on 2022-01-25 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0009_merge_20220125_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsale',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='cowsale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='goatsale',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='goatsale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='pigsale',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='pigsale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='sheepsale',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AddField(
            model_name='sheepsale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price(s)'),
        ),
    ]
