# Generated by Django 3.0.3 on 2022-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0009_pigmortality_commentp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigmortality',
            name='drysows_num',
            field=models.IntegerField(default=0, verbose_name='Dry Sow(s)'),
        ),
        migrations.AddField(
            model_name='pigmortality',
            name='growers_num',
            field=models.IntegerField(default=0, verbose_name='Grower(s)'),
        ),
        migrations.AddField(
            model_name='pigmortality',
            name='hogs_num',
            field=models.IntegerField(default=0, verbose_name='Hog(s)'),
        ),
        migrations.AddField(
            model_name='pigmortality',
            name='nursing_num',
            field=models.IntegerField(default=0, verbose_name='Nursing Mother(s)'),
        ),
        migrations.AddField(
            model_name='pigmortality',
            name='weaners_num',
            field=models.IntegerField(default=0, verbose_name='Weaner(s)'),
        ),
    ]
