# Generated by Django 4.2.19 on 2026-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0011_pendingeventedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('boar', 'Boar'), ('weaner(pig)', 'Weaner(Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('weaner_cattle', 'Weaner(Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner_sheep', 'Weaner(Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner_goat', 'Weaner(Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
    ]
