# Generated by Django 3.0.3 on 2022-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0011_cowbirth_goatbirth_pigbirth_sheepbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goatbirth',
            old_name='defected_lamb',
            new_name='defected_kid',
        ),
        migrations.AddField(
            model_name='goatbirth',
            name='comment_g',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comment'),
        ),
    ]
