# Generated by Django 3.0.3 on 2022-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0011_auto_20220125_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowcensuspop',
            name='cat_population',
        ),
        migrations.RemoveField(
            model_name='goatcensuspop',
            name='got_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='pig_population',
        ),
        migrations.RemoveField(
            model_name='sheepcensuspop',
            name='shp_population',
        ),
        migrations.AddField(
            model_name='cowcensuspop',
            name='bull_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bulls Population'),
        ),
        migrations.AddField(
            model_name='cowcensuspop',
            name='calf_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calves Population'),
        ),
        migrations.AddField(
            model_name='cowcensuspop',
            name='cow_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cows Population'),
        ),
        migrations.AddField(
            model_name='goatcensuspop',
            name='buck_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bucks Population'),
        ),
        migrations.AddField(
            model_name='goatcensuspop',
            name='doe_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Does Population'),
        ),
        migrations.AddField(
            model_name='goatcensuspop',
            name='kid_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kids Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='boar_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Boar Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='dry_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dry Sows Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='grower_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Growers Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='hog_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hogs Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='sow_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sow Population'),
        ),
        migrations.AddField(
            model_name='pigcensuspop',
            name='weaner_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weaners Population'),
        ),
        migrations.AddField(
            model_name='sheepcensuspop',
            name='ewe_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ewes Population'),
        ),
        migrations.AddField(
            model_name='sheepcensuspop',
            name='lamb_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lambs Population'),
        ),
        migrations.AddField(
            model_name='sheepcensuspop',
            name='ram_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rams Population'),
        ),
    ]
