# Generated by Django 4.2.19 on 2026-02-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmrecord', '0012_alter_animaltype_animal_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingeventedit',
            name='approved',
        ),
        migrations.AddField(
            model_name='pendingeventedit',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingeventedit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingeventedit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingeventedit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='pendingeventedit',
            name='vet_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('boar', 'Boar'), ('weaner(pig)', 'Weaner(Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('weaner(cattle)', 'Weaner(Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner(sheep)', 'Weaner(Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner(goat)', 'Weaner(Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
    ]
