# Generated by Django 3.0.3 on 2022-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0012_auto_20220125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowcensuspop',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('', 'Select month')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='goatcensuspop',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('', 'Select month')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pigcensuspop',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('', 'Select month')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheepcensuspop',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('', 'Select month')], default='', max_length=50),
        ),
    ]
