# Generated by Django 3.0.3 on 2022-07-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0013_auto_20220701_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='boar_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='dry_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='grower_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='hog_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='sow_population',
        ),
        migrations.RemoveField(
            model_name='pigcensuspop',
            name='weaner_population',
        ),
    ]
