# Generated by Django 4.2.19 on 2026-05-07 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0013_remove_pendingeventedit_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoticAnimalCensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(choices=[('geese', 'Geese'), ('crocodile', 'Crocodile')], max_length=20)),
                ('census_date', models.DateField(default=django.utils.timezone.now)),
                ('total_animals', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exotic Animal Census',
                'verbose_name_plural': 'Exotic Animal Census Records',
                'ordering': ['-census_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'ordering': ['animal_type_name']},
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('boar', 'Boar'), ('weaner (pig)', 'Weaner (Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('gilt', 'Gilt'), ('hog', 'Hog'), ('weaner (cattle)', 'Weaner (Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner (sheep)', 'Weaner (Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner (goat)', 'Weaner (Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_name',
            field=models.CharField(choices=[('mortality', 'Mortality'), ('farrowing', 'Farrowing'), ('calving', 'Calving'), ('lambing', 'Lambing'), ('kidding', 'Kidding'), ('procurement', 'Procurement'), ('culling', 'Culling'), ('sale', 'Sale'), ('treatment', 'Treatment'), ('vaccination', 'Vaccination'), ('gift', 'Gift')], max_length=20),
        ),
    ]
