# Generated by Django 4.2.19 on 2026-05-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmrecord', '0014_exoticanimalcensus_alter_animaltype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusApprovalQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_data_payload', models.JSONField(help_text='Serialized form & formset data fields')),
                ('is_processed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='farmrecord.census')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
