# Generated by Django 3.0.3 on 2022-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0014_auto_20220208_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goatsale',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Price(s)'),
        ),
    ]
