# Generated by Django 4.2.19 on 2026-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0015_censusapprovalqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='is_pending_review',
            field=models.BooleanField(default=False),
        ),
    ]
