# Generated by Django 3.0.3 on 2022-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0015_auto_20220208_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowmortality',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
