# Generated by Django 3.0.3 on 2023-11-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0016_auto_20220706_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='section',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='farmrecord.Section', verbose_name='Section'),
        ),
    ]
