# Generated by Django 4.2.19 on 2026-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0016_census_is_pending_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusapprovalqueue',
            name='request_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
