# Generated by Django 3.0.3 on 2022-02-15 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0017_auto_20220210_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowcensuspop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowculling',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of mortality'),
        ),
        migrations.AlterField(
            model_name='cowprocurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goatcensuspop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goatculling',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of mortality'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goatprocurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pigcensuspop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pigculling',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of mortality'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pigprocurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheepcensuspop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheepculling',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Cause of mortality'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheepprocurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
