# Generated by Django 4.2.19 on 2026-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0017_censusapprovalqueue_request_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusapprovalqueue',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name="Admin's Feedback Note"),
        ),
        migrations.AlterField(
            model_name='censusapprovalqueue',
            name='request_note',
            field=models.TextField(blank=True, null=True, verbose_name="Vet's Request Note"),
        ),
    ]
