# Generated by Django 4.2.19 on 2026-07-07 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0018_censusapprovalqueue_admin_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('dry sow', 'Dry Sow'), ('boar', 'Boar'), ('weaner (pig)', 'Weaner (Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('gilt', 'Gilt'), ('hog', 'Hog'), ('weaner (cattle)', 'Weaner (Cattle)'), ('calf', 'Calf'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner (sheep)', 'Weaner (Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner (goat)', 'Weaner (Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
    ]
