# Generated by Django 3.0.3 on 2022-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0018_auto_20220215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmortality',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='first image'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='first image'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='first image'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='first image'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name=' second image'),
        ),
    ]
