# Generated by Django 4.2.19 on 2026-07-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0019_eventtype_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiggeryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='animal_type_name',
            field=models.CharField(choices=[('sow', 'Sow'), ('dry sow', 'Dry Sow'), ('boar', 'Boar'), ('weaner (pig)', 'Weaner (Pig)'), ('piglet', 'Piglet'), ('cow', 'Cow'), ('bull', 'Bull'), ('gilt', 'Gilt'), ('hog', 'Hog'), ('weaner (cattle)', 'Weaner (Cattle)'), ('calf', 'Calf'), ('miniature cattle', 'Miniature Cattle'), ('donkey', 'Donkey'), ('ewe', 'Ewe'), ('ram', 'Ram'), ('weaner (sheep)', 'Weaner (Sheep)'), ('lamb', 'Lamb'), ('buck', 'Buck'), ('doe', 'Doe'), ('weaner (goat)', 'Weaner (Goat)'), ('kid', 'Kid')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='PiggeryCensusRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piggery_records', to='farmrecord.census')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmrecord.piggeryline')),
            ],
        ),
    ]
