# Generated by Django 3.0.3 on 2022-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0019_auto_20220215_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goatprocurement',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
        migrations.AlterField(
            model_name='sheepprocurement',
            name='size1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size(s)'),
        ),
    ]
