# Generated by Django 4.2.19 on 2026-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0020_piggeryline_alter_animaltype_animal_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggerycensusrecord',
            name='total_general',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piggerycensusrecord',
            name='total_piglets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
