# Generated by Django 3.0.3 on 2022-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0020_auto_20220215_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goatmortality',
            name='doe_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='Doe(s)'),
        ),
    ]
