# Generated by Django 4.2.19 on 2026-07-15 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmrecord', '0021_piggerycensusrecord_total_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_name',
            field=models.CharField(choices=[('mortality', 'Mortality'), ('farrowing', 'Farrowing'), ('calving', 'Calving'), ('lambing', 'Lambing'), ('kidding', 'Kidding'), ('procurement', 'Procurement'), ('culling', 'Culling'), ('sale', 'Sale'), ('treatment', 'Treatment'), ('vaccination', 'Vaccination'), ('gift', 'Gift'), ('castration', 'Castration')], max_length=20),
        ),
    ]
