# Generated by Django 3.0.3 on 2022-02-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0021_auto_20220216_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowculling',
            name='bull_num',
            field=models.IntegerField(default=0, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='cowculling',
            name='cow_num',
            field=models.IntegerField(default=0, verbose_name='Cow(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='bull_num',
            field=models.IntegerField(default=0, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='calves',
            field=models.IntegerField(default=0, verbose_name='calve(s)'),
        ),
        migrations.AlterField(
            model_name='cowmortality',
            name='cow_num',
            field=models.IntegerField(default=0, verbose_name='Cow(s)'),
        ),
        migrations.AlterField(
            model_name='cowprocurement',
            name='bull_num',
            field=models.IntegerField(default=0, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='cowprocurement',
            name='cow_num',
            field=models.IntegerField(default=0, verbose_name='Cow(s)'),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='bull_num',
            field=models.IntegerField(default=0, verbose_name='Bull(s)'),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='cow_num',
            field=models.IntegerField(default=0, verbose_name='Cow(s)'),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='cowsale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Toatl Price(s)'),
        ),
        migrations.AlterField(
            model_name='goatculling',
            name='buck_num',
            field=models.IntegerField(default=0, verbose_name='Buck(s)'),
        ),
        migrations.AlterField(
            model_name='goatculling',
            name='doe_num',
            field=models.IntegerField(default=0, verbose_name='Doe(s)'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='buck_num',
            field=models.IntegerField(default=0, verbose_name='Buck(s)'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='doe_num',
            field=models.IntegerField(default=0, verbose_name='Doe(s)'),
        ),
        migrations.AlterField(
            model_name='goatmortality',
            name='kid',
            field=models.IntegerField(default=0, verbose_name='kid(s)'),
        ),
        migrations.AlterField(
            model_name='goatprocurement',
            name='buck_num',
            field=models.IntegerField(default=0, verbose_name='Buck(s)'),
        ),
        migrations.AlterField(
            model_name='goatprocurement',
            name='doe_num',
            field=models.IntegerField(default=0, verbose_name='Doe(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='buck_num',
            field=models.IntegerField(default=0, verbose_name='Buck(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='doe_num',
            field=models.IntegerField(default=0, verbose_name='Doe(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='goatsale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price(s)'),
        ),
        migrations.AlterField(
            model_name='pigculling',
            name='boar_num',
            field=models.IntegerField(default=0, verbose_name='Boar(s)'),
        ),
        migrations.AlterField(
            model_name='pigculling',
            name='sow_num',
            field=models.IntegerField(default=0, verbose_name='Sow(s)'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='boar_num',
            field=models.IntegerField(default=0, verbose_name='Boar(s)'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='pigglet',
            field=models.IntegerField(default=0, verbose_name='Pigglet(s)'),
        ),
        migrations.AlterField(
            model_name='pigmortality',
            name='sow_num',
            field=models.IntegerField(default=0, verbose_name='Sow(s)'),
        ),
        migrations.AlterField(
            model_name='pigprocurement',
            name='boar_num',
            field=models.IntegerField(default=0, verbose_name='Boar(s)'),
        ),
        migrations.AlterField(
            model_name='pigprocurement',
            name='sow_num',
            field=models.IntegerField(default=0, verbose_name='Sow(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='boar_num',
            field=models.IntegerField(default=0, verbose_name='Boar(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='sow_num',
            field=models.IntegerField(default=0, verbose_name='Sow(s)'),
        ),
        migrations.AlterField(
            model_name='pigsale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price(s)'),
        ),
        migrations.AlterField(
            model_name='sheepculling',
            name='ewe_num',
            field=models.IntegerField(default=0, verbose_name='Ewe(s)'),
        ),
        migrations.AlterField(
            model_name='sheepculling',
            name='ram_num',
            field=models.IntegerField(default=0, verbose_name='Ram(s)'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='ewe_num',
            field=models.IntegerField(default=0, verbose_name='Ewe(s)'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='lamb',
            field=models.IntegerField(default=0, verbose_name='lamb(s)'),
        ),
        migrations.AlterField(
            model_name='sheepmortality',
            name='ram_num',
            field=models.IntegerField(default=0, verbose_name='Ram(s)'),
        ),
        migrations.AlterField(
            model_name='sheepprocurement',
            name='ewe_num',
            field=models.IntegerField(default=0, verbose_name='Ewe(s)'),
        ),
        migrations.AlterField(
            model_name='sheepprocurement',
            name='ram_num',
            field=models.IntegerField(default=0, verbose_name='Ram(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='ewe_num',
            field=models.IntegerField(default=0, verbose_name='Ewe(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Price(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='ram_num',
            field=models.IntegerField(default=0, verbose_name='Ram(s)'),
        ),
        migrations.AlterField(
            model_name='sheepsale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price(s)'),
        ),
    ]
