# Generated by Django 4.2.19 on 2026-07-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0022_census_logged_by_eventtype_logged_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_count', models.PositiveIntegerField()),
                ('projected_count', models.PositiveIntegerField()),
                ('total_mortality', models.PositiveIntegerField(default=0)),
                ('total_culling', models.PositiveIntegerField(default=0)),
                ('total_sale', models.PositiveIntegerField(default=0)),
                ('total_gift', models.PositiveIntegerField(default=0)),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('total_procurement', models.PositiveIntegerField(default=0)),
                ('census', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projection_data', to='farmrecord.census')),
            ],
        ),
    ]
