# Generated by Django 3.0.3 on 2022-02-17 15:58

from django.db import migrations, models
from farmapp.utils import unique_slug_generator


def update_slugcm(apps, schema_editor):
    CowMortality = apps.get_model("farmrecord", "CowMortality")

    for instance in CowMortality.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     
def update_sluggm(apps, schema_editor):
    GoatMortality = apps.get_model("farmrecord", "GoatMortality")

    for instance in GoatMortality.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_slugsm(apps, schema_editor):
    SheepMortality = apps.get_model("farmrecord", "SheepMortality")

    for instance in SheepMortality.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_slugpm(apps, schema_editor):
    PigMortality = apps.get_model("farmrecord", "PigMortality")

    for instance in PigMortality.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_slugcc(apps, schema_editor):
    CowCulling = apps.get_model("farmrecord", "CowCulling")

    for instance in CowCulling.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_sluggc(apps, schema_editor):
    GoatCulling = apps.get_model("farmrecord", "GoatCulling")

    for instance in GoatCulling.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_slugsc(apps, schema_editor):
    SheepCulling = apps.get_model("farmrecord", "SheepCulling")

    for instance in SheepCulling.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     

def update_slugpc(apps, schema_editor):
    PigCulling = apps.get_model("farmrecord", "PigCulling")

    for instance in PigCulling.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.location, instance.slug)
            instance.save()
     


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0022_auto_20220216_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowculling',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cowmortality',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='goatculling',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='goatmortality',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pigculling',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pigmortality',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sheepculling',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sheepmortality',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.RunPython(update_slugcm, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_sluggm, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_slugsm, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_slugpm, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_slugcc, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_sluggc, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_slugsc, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_slugpc, reverse_code=migrations.RunPython.noop),
        
        
    ]
