# Generated by Django 3.0.3 on 2022-02-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmrecord', '0024_auto_20220217_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=100, verbose_name='Department')),
                ('dpt_desc', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmrecord.Department', verbose_name='Department'),
        ),
    ]
