# Generated by Django 3.0.3 on 2022-07-20 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psec_name', models.CharField(max_length=50, verbose_name='Purchse name')),
                ('psec_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity/Amount')),
                ('i_price', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Price per Quantity')),
                ('price', models.IntegerField(max_length=50, verbose_name='Total Price')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PurchaseSection', verbose_name='Section')),
            ],
        ),
    ]
