# Generated by Django 3.0.3 on 2022-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_SN', models.CharField(max_length=100, verbose_name='Surname')),
                ('employee_MN', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('employee_FN', models.CharField(max_length=100, verbose_name='First Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone', models.IntegerField(max_length=50, verbose_name='Phone Number')),
            ],
        ),
    ]
