# Generated by Django 3.0.3 on 2022-03-21 10:35

from django.db import migrations, models
import django.utils.timezone
import farmrecord.validators


class Migration(migrations.Migration):

    dependencies = [
        ('humanR', '0002_auto_20220317_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bvn',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bank Verification Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='guarantor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guarantor Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='I.D NO.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farmrecord.validators.validate_file_size], verbose_name='first image'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_oname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other names'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship With employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('', 'Select sex')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
