# Generated by Django 3.0.3 on 2022-03-21 14:18

from django.db import migrations, models
from farmapp.utils import unique_slug_generatorEMP



def update_slugb(apps, schema_editor):
    Employee = apps.get_model('humanR', 'Employee')

    for instance in Employee.objects.all():
      if not instance.slug:
        instance.slug = unique_slug_generatorEMP(instance, instance.employee_SN, instance.slug)
        instance.save()  

class Migration(migrations.Migration):

    dependencies = [
        ('humanR', '0003_auto_20220321_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.RunPython(update_slugb, reverse_code=migrations.RunPython.noop)
    ]
