# Generated by Django 3.0.3 on 2022-03-21 14:28

from django.db import migrations, models
from farmapp.utils import unique_slug_generatorEMP

def update_slugb(apps, schema_editor):
    Employee = apps.get_model('humanR', 'Employee')

    for instance in Employee.objects.all():
      if not instance.slug:
        instance.slug = unique_slug_generatorEMP(instance, instance.employee_SN, instance.slug)
        instance.save()  


class Migration(migrations.Migration):

    dependencies = [
        ('humanR', '0004_employee_slug'),
    ]

    operations = [
        migrations.RunPython(update_slugb, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
