# Generated by Django 3.0.3 on 2022-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanR', '0007_auto_20220323_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Description'),
        ),
    ]
