# Generated by Django 3.0.3 on 2022-06-22 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('humanR', '0009_auto_20220331_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('remind_title', models.CharField(max_length=200, verbose_name='Remind about')),
                ('remind_description', models.TextField(max_length=500, verbose_name='Description about reminder')),
                ('remind_date', models.DateField()),
            ],
        ),
    ]
